### ISSUE TITLE
Appveyor builds fail due to unicode em-dash

### ISSUE THREAD

**Issue by nealrichardson** [Crunch-io/crunchtabs#40]
Failure looks like 

```
-- 1. Failure: Write Latex crosstab (@test-write-latex.R#31)  ------------------
`tex` not identical to `ref`.
4/723 mismatches
x[178]: "\\addcontentsline{lot}{table}{ 3A. Name the kinds of pets you have at the
x[178]: se locations. � Home}"
y[178]: "\\addcontentsline{lot}{table}{ 3A. Name the kinds of pets you have at the
y[178]: se locations. �\200� Home}"
```

That's from this line: https://github.com/Crunch-io/crunchtabs/blob/67cd8ce05c6c40cc3e7d9b0b148f4ac11f8dcfa1/R/tex-table.R#L361

I'm not sure if this suggests a general Windows failure, or if this is specific to Appveyor's configuration, or the test environment, or what. Not sure how much it matters since there are alternatives within LaTeX. We could probably just do `---` instead, but some googling suggests that `\textemdash` might work best when using other fonts. Should be a quick fix, only slowed by needing to check that the PDFs are right and then updating the fixture .tex files.

**Comment by malecki** [comment]
@1beb we stopped using appveyor in in favor of travis in rcrunch and crplyr, you might consider doing the same to get rid of a failbadge. I don't remember the details of why we couldn't switch to github actions. https://github.com/Crunch-io/rcrunch/commit/866b7789a24d396a7b34212849bf46a7f9a70c1b

**Comment by 1beb** [comment]
@malecki I'll remove appveyor in favour of travis. I am using github actions (internally too). So if there is a reason why we aren't supposed to use it, I'd like to know. 

This error is environment based, but to the tex installation. I strongly recommend we enforce a hard requirement on tinytex to avoid having to support miketex/texlive. Yihui has done a really good job with ti. Enforcing it's use also narrows scope of support requirements for other tex installations peculiarities (of which there are many).

My first run through this code I think I solved this problem here: https://github.com/Crunch-io/crunchtabs/pull/44/files#diff-75cc5c60092b17cdf5a0ee23fa082494R110-R117

**Comment by 1beb** [comment]
No longer using appveyor. Closing.
